### ISSUE TITLE
how to proxy bitbucket's private repos 

### ISSUE THREAD

**Issue by zhuzhengyang** [cezarguimaraes/pkgsite#2]
I have some private golang repositories on bitbucket, I just want to show their go doc, no other public libraries, how should I configure it. 
I understand that I need to get pkgsite to connect to own athens, but I've tried some configurations without success.

**Comment by cezarguimaraes** [comment]
Hello @zhuzhengyang , your question could be best answered by the folks over at athens https://github.com/gomods/athens/issues
That said, if username/password authentication is suitable for your use case, you could provide athens with a `.netrc` file.
Please refer to atlassian's documentation on [.netrc files](https://confluence.atlassian.com/bitbucketserver/permanently-authenticating-with-git-repositories-776639846.html#PermanentlyauthenticatingwithGitrepositories-Usingthe.netrcfile)
With a working `.netrc` file in hand, you would create a [kubernetes secret containing your file](https://docs.gomods.io/install/install-on-kubernetes/#netrc-file-support) and enable it via values in this chart.

```yaml
athens-proxy:
  netrc:
    enabled: true
    existingSecret: netrcsecret
```

**Comment by zhuzhengyang** [comment]
Thanks for the pointer.
