### ISSUE TITLE
Contributing chart parameters extraction for seeddb job

### ISSUE THREAD

**Issue by natigavriel** [cezarguimaraes/pkgsite#4]
Hello @cezarguimaraes ,
I would like to use your chart as a dependency to my project.
I needed to inject several parameters (i.e : imagePullSecrets, backoffLimit) to the seeddb job template so it would fit my project.
To my understanding this small change add 2 more generic configuration so it an be useful to all stakeholders as well.

I have already created a PR - https://github.com/cezarguimaraes/pkgsite/pull/3
Can you please consider merging this change ?
 
Best Regards :-)

**Comment by cezarguimaraes** [comment]
Closed by #3 , thank you again for your contribution !
Chart version 0.3.0 has been released
