### ISSUE TITLE
Support job scheduling on a dedicated node

### ISSUE THREAD

**Issue by natigavriel** [cezarguimaraes/pkgsite#6]
Hi @cezarguimaraes 

Support job scheduling on a dedicated node by exposing nodeSelector, tolerations and affinity.
Can you kindly review this contribution and merge if acceptable ?
Link - https://github.com/cezarguimaraes/pkgsite/pull/5

Best regard,
@natigavriel

**Comment by cezarguimaraes** [comment]
Closed by #5 
Chart version 0.4.0 has been released, thank you!
